# This is a basic workflow to help you get started with Actions

name: Github CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-linux"
  build-linux:
    # The type of runner that the job will run on (ubuntu-latest or ubuntu-18.04)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Update apt-packages
        run: sudo apt-get update
      
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: sudo apt-get install g++-multilib libopenal-dev libpulse-dev libsdl2-dev
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run rebuild scripts
        run: |
          pwd
          cd scripts
          ./rebuildmods.sh
          ./rebuildwake.sh
          ./rebuildwide.sh
          ./rebuildlauncher.sh
          ./makedocs.sh
  # This workflow contains a single job called "build-windows"
  build-windows:
    # The type of runner that the job will run on (ubuntu-latest)
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run rebuild scripts
        shell: cmd
        run: |
          echo %CD%
          cd %CD%\scripts
          rebuildall.bat
  # This workflow contains a single job called "build-macos"
  build-macos:
    # The type of runner that the job will run on (macos-latest)
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run rebuild scripts
        run: |
          pwd
          cd scripts
          ./rebuildmods.sh
          ./rebuildwake.sh
          ./rebuildwide.sh
          ./rebuildlauncher.sh
          ./makedocs.sh
